### ISSUE TITLE
Add White Oak Asset Management S.A.

### ISSUE THREAD

**Issue by rca22** [fsprojects/fsharp-companies#111]
Please can you add White Oak Asset Management S.A. to the list? We are a Geneva, Switzerland based hedge fund manager. Our codebase is 99% F#, and is used for research, trade execution and risk systems. Please feel free to ask any follow up questions.

**Comment by Swoorup** [comment]
I am curious what sort of technologies do you employ? Micro-services, database, event sourcing?

**Comment by moodmosaic** [comment]
Are you using any tools for PBT like fsharp-hedgehog, FsCheck, etc?

**Comment by rca22** [comment]
@moodmosaic we are big users of FsCheck - in fact we couldn't live without its ability to construct semantically valid instances of complicated types through combining generators.

**Comment by jayhill** [comment]
@rca22 If you'd still like White Oak Asset Management added to this list, could you please submit a pull request with the proposed addition?
