### ISSUE TITLE
Move to fsprojects? 

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fsharp-companies#154]
Hi Kevin, 

If you like you can move this to "fsprojects" org to have it somewhere neutral with multiple maintainers.

Best
Don

**Comment by Kavignon** [comment]
So I wouldn't be the main maintainer for the project? How would the process look like?

**Comment by dsyme** [comment]
You would be main maintainer, plus anyone else you decide - it's more there would always be backup maintainers per the policies :) 

Policies are here: https://github.com/fsprojects/fsprojects-admin/blob/master/README.md

**Comment by Kavignon** [comment]
I accept! How would that work specifically, the process?

**Comment by dsyme** [comment]
First see if you can transfer it in, via settings, at the bottom of the main page. If you're a member of the fsprojects org you will be able to. If not check for an invite, I'll send one now

**Comment by dsyme** [comment]
Sent. Accept the invitation then you should be able to transfer. We may have to fix up permissions once you transfer it

**Comment by Kavignon** [comment]
@dsyme the move was completed!

**Comment by Kavignon** [comment]
What's the next step?

**Comment by dsyme** [comment]
That's it really! We can send tweets and messages around announcing it's fine. The redirects  happen automatically

**Comment by dsyme** [comment]
See https://mobile.twitter.com/dsymetweets/status/1481027138140708864

You still have full admin rights over the repo, please make sure everyone you want has maintener rights :)
