### ISSUE TITLE
Add PodGroup

### ISSUE THREAD

**Issue by javicabanas** [fsprojects/fsharp-companies#183]
PodGroup is an IoT connectivity company within Gieseke+Devrient based in Seville. It is implemented using microservices and some of them have been implemented entirely with F# with Azure Functions.

Currently there is a vacancy for an engineer profile in F#, based in Seville.

Please, add PodGroup to the list in https://github.com/fsprojects/fsharp-companies.

-	Name: PodGroup -  A Giesecke+Devrient Company 
-	Location: Seville (Spain)
-	Sector: IoT
-	Remote OK: No

**Comment by bartelink** [comment]
Normally people prepare a PR to the README, so a committer can simply and quickly merge it when visiting...
